#!/bin/sh

# Can't find tty without this
mv /dev/tty /dev/tty-bak && cp -a /dev/console /dev/tty

# Daemonize the agent
gpg-agent --homedir /root/.gnupg --use-standard-socket --daemon

# Connect the gpg-agent
gpg-connect-agent /bye

GPG_TTY=/dev/tty
export GPG_TTY
