#!/bin/sh

###############################################################
# Build Static Busybox

source /etc/portage/make.conf

BUSYBOX_BIN=$WORKDIR/bin/busybox
if [ ! -x $ECLODIR_STATIC/busybox ] ; then
  PKG=sys-apps/busybox
  BUSYBOX_EBUILD=$(ls /usr/portage/$PKG/*.ebuild | head -n 1)
  BUSYBOX_EBUILD=${BUSYBOX_EBUILD##*/}
  echo "[+] Building $BUSYBOX_EBUILD, plz wait ..."
  USE="-pam static" ebuild /usr/portage/$PKG/$BUSYBOX_EBUILD clean unpack compile
  if [ $? -ne 0 ] ; then
    echo "[-] Failed to build $BUSYBOX_EBUILD"
    exit 1
  fi
  (cp /var/tmp/portage/${PKG%/*}/${BUSYBOX_EBUILD%.*}/work/${BUSYBOX_EBUILD%.*}/busybox $ECLODIR_STATIC/busybox)
  ebuild /usr/portage/$PKG/$BUSYBOX_EBUILD clean
elif ldd $ECLODIR_STATIC/busybox >/dev/null ; then
  echo "[-] Busybox is not static"
  exit 1
else
  echo "[+] Busybox found" >>$LOG
fi

cp -a $ECLODIR_STATIC/busybox $BUSYBOX_BIN
BUSY_BIN=$(type -p $BUSYBOX_BIN)
BUSY_APPS=/tmp/busybox-apps
$BUSY_BIN --list-full > $BUSY_APPS

# Remove some links from $BUSY_APPS
for l in busybox blkid sha1sum sha3sum ssl_client su \
  telnet raidautorun adduser addgroup acpid ; do
  eval sed -i '/$l/d' $BUSY_APPS
done

###############################################################
# Create links

for bin in $(grep -e '^bin/[a-z]' $BUSY_APPS) ; do
  ln -s busybox $bin 
done

for sbin in $(grep -e '^sbin/[a-z]' $BUSY_APPS) ; do
  ln -s ../bin/busybox $sbin
done
