#!/usr/bin/env sh

addTheKey() {
  mkdir -p root
  cp -a "$EXT_KEY" root/"${EXT_KEY##*/}" 2>>"$LOG"
  err=$?
  if [ $err -eq 0 ] ; then
    echo "[+] $EXT_KEY copied at /root/${EXT_KEY##*/}"
    chmod 600 root/"${EXT_KEY##*/}"
  else
    echo "[-] Failed to copy your key $EXT_KEY"
    exit 1
  fi
}

[ -f "$EXT_KEY" ] || die "[-] Key $EXT_KEY is no found..."

addTheKey
