#!/usr/bin/env sh

mkdir -p usr/share/gnupg root/.gnupg usr/bin

bins="${bins} gpg gpg-agent gpgconf gpg-connect-agent pinentry-curses"
modules="${modules} cast5"

# Make the link of pinentry
cd usr/bin && ln -s pinentry-curses pinentry
cd "$WORKDIR" || exit 1

# Configure the agent
cat > root/.gnupg/gpg.conf << EOF
use-agent
pinentry-mode loopback
EOF

echo "allow-loopback-pinentry" > root/.gnupg/gpg-agent.conf

chmod 700 root/.gnupg
