#!/usr/bin/env sh

# No reason to change keymap all times if work
[ -f /etc/eclosion/keymaps ] || {
  loadkeys -b -u "$KEYMAP" > /etc/eclosion/keymaps
  res=$?
  if [ $res -eq 0 ] ; then
    echo "[+] Add $KEYMAP to the initramfs"
  else
    die "Fail to add $KEYMAP"
  fi
}

mkdir -p usr/share/keymaps
cp /etc/eclosion/keymaps usr/share/keymaps/keyboard.bin
