#!/bin/sh

########################################################
# Mdev Setup

# mdev and udev need /etc/group
cp -a /etc/group etc/group

cat > etc/mdev.conf << EOF
\$MODALIAS=.*	0:0 660 @modprobe "\$MODALIAS"

null		0:0 666 @chmod 666 \$MDEV
zero		0:0 666
full		0:0 666
random		0:0 444
urandom		0:0 444
hwrandom	0:0 444
grsec		0:0 660

kmem		0:0 640
mem		0:0 640
port		0:0 640
console		0:5 600 @chmod 600 \$MDEV
ptmx		0:5 666
pty.*		0:5 660

tty		0:5 666
tty[0-9]*	0:5 660
vcsa*[0-9]*	0:5 660
ttyS[0-9]*	0:14 660

ram([0-9]*)	0:6 660 >rd/%1
loop([0-9]+)	0:6 660 >loop/%1
sd[a-z].*	0:6 660 */lib/mdev/storage-device
hd[a-z].*	0:6 660 */lib/mdev/storage-device
vd[a-z].* 0:6 660 */lib/mdev/storage-device
dm-[0-9]* 0:6 660 */lib/mdev/storage-device
bcache[0-9]* 0:6 660 */lib/mdev/storage-device

fuse		0:0 666

event[0-9]+	0:0 640 =input/
mice		0:0 640 =input/
mouse[0-9]	0:0 640 =input/
ts[0-9]		0:0 600 =input/

usbdev[0-9]*	0:0 660
EOF

mkdir -p lib/mdev
cp /lib/mdev/ide_links lib/mdev/
if [ ! -f $ECLODIR_STATIC/storage-device ] ; then
  wget -P $ECLODIR_STATIC/ https://raw.githubusercontent.com/slashbeast/mdev-like-a-boss/master/helpers/storage-device
  chmod +x $ECLODIR_STATIC/storage-device
fi

cp -a $ECLODIR_STATIC/storage-device lib/mdev/
